# Deploy config
- hosts: 'all'
  gather_facts: yes
  become: yes
  tasks:
    - name: deploy config
      template: 
            src=templates/dbconfig-default.j2
            dest=/home/blaze/db.cfg
            owner=root
            group=root
            mode=0755
